<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="HEU-PEDRO-PRADIITA" failures="1" tests="3" name="HomePage" time="378.645" errors="0" timestamp="2021-10-18T08:50:38 ICT">
  <testcase classname="pintaria.PintariaHomeTest" name="HomeBodyUrl" time="114.701">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	The link with https://pintaria.id/s1-manajemen-azzahra is broken with code 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The link with https://pintaria.id/s1-manajemen-azzahra is broken with code 404 expected [true] but found [false]
at pintaria.PintariaHomeTest.HomeBodyUrl(PintariaHomeTest.java:192)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- HomeBodyUrl -->
  <testcase classname="pintaria.PintariaHomeTest" name="HomeFooterUrl" time="114.205"/>
  <testcase classname="pintaria.PintariaHomeTest" name="HomeHeaderUrl" time="83.965"/>
  <testcase classname="pintaria.PintariaHomeTest" name="SuccessInput" time="0.0">
    <ignored/>
  </testcase> <!-- SuccessInput -->
  <testcase classname="pintaria.PintariaHomeTest" name="HomeAlert" time="0.0">
    <ignored/>
  </testcase> <!-- HomeAlert -->
</testsuite> <!-- HomePage -->
