<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HEU-PEDRO-PRADIITA" failures="1" tests="9" name="LoginPage" time="92.301" errors="0" timestamp="6 Nov 2021 07:46:34 GMT">
  <testcase classname="brick.BrickLoginTest" name="EmailText" time="0.133"/>
  <testcase classname="brick.BrickLoginTest" name="ForgotPasswordTextLink" time="2.488">
    <failure type="java.lang.AssertionError" message="The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]
	at brick.BrickLoginTest.ForgotPasswordTextLink(BrickLoginTest.java:105)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ForgotPasswordTextLink -->
  <testcase classname="brick.BrickLoginTest" name="Login" time="0.0">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="brick.BrickLoginTest" name="LoginAlert" time="1.936"/>
  <testcase classname="brick.BrickLoginTest" name="LoginText" time="0.066"/>
  <testcase classname="brick.BrickLoginTest" name="LogoBrick" time="0.065"/>
  <testcase classname="brick.BrickLoginTest" name="Membertext" time="0.085"/>
  <testcase classname="brick.BrickLoginTest" name="PasswordText" time="0.071"/>
  <testcase classname="brick.BrickLoginTest" name="SignUpTextLink" time="2.766"/>
</testsuite> <!-- LoginPage -->
