<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HEU-PEDRO-PRADIITA" failures="1" tests="9" name="LoginPage" time="79.105" errors="0" timestamp="22 Oct 2021 04:11:50 GMT">
  <testcase classname="brick.BrickLoginTest" name="EmailText" time="0.052"/>
  <testcase classname="brick.BrickLoginTest" name="ForgotPasswordTextLink" time="3.678">
    <failure type="java.lang.AssertionError" message="The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]
	at brick.BrickLoginTest.ForgotPasswordTextLink(BrickLoginTest.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ForgotPasswordTextLink -->
  <testcase classname="brick.BrickLoginTest" name="Login" time="7.307"/>
  <testcase classname="brick.BrickLoginTest" name="LoginAlert" time="1.849"/>
  <testcase classname="brick.BrickLoginTest" name="LoginText" time="0.046"/>
  <testcase classname="brick.BrickLoginTest" name="LogoBrick" time="0.04"/>
  <testcase classname="brick.BrickLoginTest" name="Membertext" time="0.043"/>
  <testcase classname="brick.BrickLoginTest" name="PasswordText" time="0.048"/>
  <testcase classname="brick.BrickLoginTest" name="SignUpTextLink" time="1.36"/>
</testsuite> <!-- LoginPage -->
