<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HEU-PEDRO-PRADIITA" failures="1" tests="9" name="brick.BrickLoginTest" time="78.762" errors="0" timestamp="22 Oct 2021 04:13:39 GMT">
  <testcase classname="brick.BrickLoginTest" name="LoginText" time="7.100"/>
  <testcase classname="brick.BrickLoginTest" name="PasswordText" time="8.979"/>
  <testcase classname="brick.BrickLoginTest" name="Login" time="17.248"/>
  <testcase classname="brick.BrickLoginTest" name="EmailText" time="5.650"/>
  <testcase classname="brick.BrickLoginTest" name="ForgotPasswordTextLink" time="9.228">
    <failure message="The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The link with https://brick-qa-assignment.herokuapp.com/forgot is broken with code 404 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at brick.BrickLoginTest.ForgotPasswordTextLink(BrickLoginTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- ForgotPasswordTextLink -->
  <testcase classname="brick.BrickLoginTest" name="Membertext" time="9.452"/>
  <testcase classname="brick.BrickLoginTest" name="LogoBrick" time="5.595"/>
  <testcase classname="brick.BrickLoginTest" name="SignUpTextLink" time="6.687"/>
  <testcase classname="brick.BrickLoginTest" name="LoginAlert" time="8.823"/>
</testsuite> <!-- brick.BrickLoginTest -->
